### ISSUE TITLE
Support to only show specific symbols

### ISSUE THREAD

**Issue by beeper99** [xnth97/SymbolPicker#10]
Hi, I love it and thanks for your efforts.
I would love to be able to specify specific icons that are the only ones shown, for example I just want the circle.fill ones as they match my app.

If there was some way to provide a list it would be great.

**Comment by xnth97** [comment]
@Moonmonkey-Beep thanks for the suggestion. That's a valid use case. In v1.5.3 I've exposed `Symbols.shared.filter` so that you can pass a block and decide which symbols you want

**Comment by beeper99** [comment]
Thanks so much, this is great.
