### ISSUE TITLE
Selected icon is displayed as white on white when in dark mode on iOS

### ISSUE THREAD

**Issue by penyaev** [xnth97/SymbolPicker#12]
In your source code, `selectedItemBackgroundColor == Color.accentColor`, which means white on iOS dark mode. At the same time, `foregroundColor` is set to `.white` no matter what. As a result, in dark mode selected icon is displayed as white icon on white background.

Suggested fix: do not hardcode `.white` but rather use a color that is dependent on the preferred color scheme, in this case `UIColor.systemBackground` might a good option since it would essential mean that for selected item, foreground and background colors are swapped.

![image](https://github.com/user-attachments/assets/87fe095a-cc62-4cb0-96f6-72586042ddd8)

**Comment by xnth97** [comment]
Hi @penyaev by default `accentColor` should be `systemBlue`. From "cancel" button in your screenshot seems that you have configured dark accent color to be white.

**Comment by penyaev** [comment]
@xnth97 you are right, apologies for the confusion. I misconfigured my accent color indeed. Thanks for your help!
